### POST reactionTimeRoutes
POST http://localhost:2020/reactionTime
Content-Type: application/json

{
    "username": "Fra",
    "time": "5.03"
}

### GET leaderboard
GET  http://localhost:2020/reactionTime

### GET leaderboard
GET  http://localhost:2020/stopwatchTester